name: Workflow with multiple jobs
on: 
    push:
        branches: 
            - main
            - '!feature/*' #ignoring pushing to any branch name starting with feature using !
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:
            - README.md #workflow will only run when a pull request that includes a change on any file rather than README.md
        branches:
            - main #configures your workflow to only run on pull request that target specific branches
env: 
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
jobs:
    Build_job:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build and upload artifact
              run: |
                echo docker build -t $CONTAINER_REGISTRY/{{vars.$DOCKER_USERNAME}}/$IMAGE_NAME:latest
                echo docker login --username={{vars.$DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD }}
                echo docker push $CONTAINER_REGISTRY/{{vars.$DOCKER_USERNAME}}/$IMAGE_NAME:latest

    Deploy_job:
        needs: [Build_job] 
        timeout-minutes: 1 #automatically cancel the job after 1 minute
        concurrency:
            group: production-deployment
            cancel-in-progress: false #wait for the other deploy job to be completed
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/{{vars.$DOCKER_USERNAME}}/$IMAGE_NAME:latest
