name: Workflow with multiple jobs
on: push
env: 
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: dockerUsername
    DOCKER_PASSWORD: s3cUrePassw0rd
    IMAGE_NAME: github-actions-nginx
jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build and upload artifact
              run: |
                docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
                docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
                docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    Deploy_job:
        needs: [Build_job] 
        runs-on: ubuntu-latest
        steps:
            - name: Docker 
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
