name: first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and read files
          run: |
            echo "My first workflow"
            ls -ltra 
            cat README.md

        - name: Execute shell script
          run: ./ascii-run.sh

        - name: List repo files
          run: ls -ltra
            