name: first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "My first workflow"

        - name: List Files
          run: ls
          
        - name: Read file
          run: cat README.md