name: first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and read files
          run: |
            echo "My first workflow"
            ls -ltra 
            cat README.md

        - name: Generate ASCII Artwork
          run: |
            sudo apt-get install cowsay -y 
            cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt
            grep -i "dragon" dragon.txt
            cat dragon.txt